server.port=8081
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=Zaq12wsx
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#
#spring.application.name=Bootstrap Spring Boot
#spring.security.user.name=sa

//do skonfigurowania po??czenie z ssms
spring.datasource.url=jdbc:sqlserver://adres_bazy_danych:port/nazwa_bazy_danych
spring.datasource.username=uzytkownik
spring.datasource.password=haslo
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect